---
title: "First Order Markov Chain Model"
output: 
  html_document:
    fig_width: 12
    fig_height: 12
---

```{r packages, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(here)
library(ggplot2)
library(lubridate)
library(reshape2)
library(viridis)
library(RColorBrewer)
library(tidyr)
library(hydroGOF)
library(stringr)
library(knitr)
library(kableExtra)
library(rnaturalearthdata)
library(rnaturalearth)
library(ggrepel)
library(sp)
library(tibble)
library(verification)
library(purrr)
library(dplyr)
```

```{r setup, include=FALSE}
source(here("src", "helper_funs.R"))

zm <- readRDS(here("data", "station", "cleaned", "zambia_station_cleaned.RDS"))
if(anyDuplicated(zm %>% dplyr::select(station, date))) stop("Duplicates found!")
zm <- zm %>% 
  dplyr::select(station, date, rain, chirps_rain, chirp_rain, era5_rain, tamsat_rain, agera5_rain)
# 1 Aug = 214
s_doy_start <- 214
zm <- zm %>% mutate(doy = yday_366(date),
                    year = year(date),
                    month = month(date),
                    s_doy = (doy - s_doy_start + 1) %% 366,
                    s_doy = ifelse(s_doy == 0, 366, s_doy),
                    syear = year,
                    syear = ifelse(s_doy > (366 - s_doy_start + 1), syear - 1, syear),
                    month = factor(month, levels = c(8:12, 1:7)),
                    month_abb = factor(month, labels = month.abb[c(8:12, 1:7)]),
                    rain = ifelse(rain < 0, 0, rain),
                    era5_rain = ifelse(era5_rain < 0, 0, era5_rain),
                    chirps_rain = ifelse(chirps_rain < 0, 0, chirps_rain), 
                    chirp_rain = ifelse(chirp_rain < 0, 0, chirp_rain), 
                    tamsat_rain = ifelse(tamsat_rain < 0, 0, tamsat_rain),
                    agera5_rain = ifelse(agera5_rain <0, 0, agera5_rain)
                    )

zm_long_st <- zm %>% 
  melt(id.vars = c("station", "date", "year", "syear", "month", "month_abb", 
                   "doy", "s_doy", "rain"),
       measure.vars = names(zm)[endsWith(names(zm), "rain")][-1],
       variable.name = "product", value.name = "pr_rain")

zm_long <- zm %>% 
  melt(id.vars = c("station", "date", "year", "syear", "month", "month_abb", "doy", "s_doy"),
       measure.vars = names(zm)[endsWith(names(zm), "rain")],
       variable.name = "product", value.name = "rain") %>%
  mutate(rainday = rain > 1)

zm_long$product <- recode(zm_long$product, rain = "station")

stations <- c("Moorings", "Choma", "Kasama", "Livingstone", "Magoye", "Mansa", "Mpika", "Chipata", "Petauke")
products <- levels(zm_long$product)
products <- products[-1]
names(products) <- substr(products, 1, nchar(products) - 5)

metadata_zm <- readRDS(here("data", "station", "cleaned", "zambia_station_metadata_cleaned.RDS"))

metadata_zm$station <- factor(metadata_zm$station, levels = stations)
zm_long$station <- factor(zm_long$station, levels = stations)

by_station <- zm_long %>%
  group_by(station) %>%
  filter(!is.na(rain) & product == "station") %>%
  summarise(first_date = first(date),
            last_date = last(date))

metadata_zm <- left_join(metadata_zm, by_station, by = "station")
rm(by_station)

zm_long <- left_join(zm_long, metadata_zm, by = "station")

zm_long <- zm_long %>% 
  filter(date >= first_date & date <= last_date)

skable <- function(kable_input) {
  kable_input %>% kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                                full_width = FALSE)
}
```

```{r}
metadata_zm %>% 
  dplyr::select(station, latitude, longitude, first_date, last_date) %>%
  kable(digits = 2) %>%
  skable()
```

```{r, include=FALSE}
station_min_date <- min((zm %>% filter(!is.na(rain) ))$date)
station_max_date <- max((zm %>% filter(!is.na(rain) ))$date)

chirps_min_date <-  min((zm %>% filter(!is.na(chirps_rain) ))$date)
chirps_max_date <-  max((zm %>% filter(!is.na(chirps_rain) ))$date)

chirp_min_date <- min((zm %>% filter(!is.na(chirp_rain) ))$date)
chirp_max_date <-  max((zm %>% filter(!is.na(chirp_rain) ))$date)

agera5_min_date <-  min((zm %>% filter(!is.na(agera5_rain) ))$date)
agera5_max_date <-  max((zm %>% filter(!is.na(agera5_rain) ))$date)

tamsat_min_date <-  min((zm %>% filter(!is.na(tamsat_rain) ))$date)
tamsat_max_date <-  max((zm %>% filter(!is.na(tamsat_rain) ))$date)

era5_min_date <-  min((zm %>% filter(!is.na(era5_rain) ))$date)
era5_max_date <-  max((zm %>% filter(!is.na(era5_rain) ))$date)

min_date <- max(station_min_date, chirps_min_date, chirp_min_date, agera5_min_date, tamsat_min_date, era5_min_date)
max_date <- min(station_max_date, chirps_max_date, chirp_max_date, agera5_max_date, tamsat_max_date, era5_max_date)

zm_long <- zm_long %>% 
  #filter(date >= min_date & date <= max_date)
  filter(syear >= year(min_date) & syear <= 2012)
zm_long_st <- zm_long_st %>% 
  #filter(date >= min_date & date <= max_date)
  filter(syear >= year(min_date) & syear <= 2012)
```

```{r}
moorings_chirps <- zm_long_st %>% 
  filter(station == "Moorings") %>%
   filter(product == "chirps_rain") %>% 
  mutate(rainday = rain >= 0.85)
```

```{r}
moorings_chirps$lag1 <- dplyr::lag(moorings_chirps$rainday, n=1) 
moorings_chirps$prev1 <- moorings_chirps$lag1
```

```{r}
moorings_chirps$rainday <- factor(moorings_chirps$rainday)
moorings_chirps$prev1 <- factor(moorings_chirps$prev1)
```

```{r}
moorings_chirps <- moorings_chirps %>%
  mutate(pr_rainday = pr_rain >= 0.85) %>%
  mutate(pr_prev1 = dplyr::lag(pr_rainday, n=1))
moorings_chirps$pr_rainday <- factor(moorings_chirps$pr_rainday)
moorings_chirps$pr_prev1 <- factor(moorings_chirps$pr_prev1)
```


```{r}
# Fitting first-order MC for station
form_zero_st <- rainday ~ ((cos(s_doy * 1 * 2 * pi/366) + sin(s_doy * 1 * 2 * pi/366) + 
                          cos(s_doy * 2 * 2 * pi/366) + sin(s_doy * 2 * 2 * pi/366) +
                          cos(s_doy * 3 * 2 * pi/366) + sin(s_doy* 3 * 2 * pi/366)) 
                          )
```


```{r}
form_zero_pr <- pr_rainday ~ ((cos(s_doy * 1 * 2 * pi/366) + sin(s_doy * 1 * 2 * pi/366) + 
                          cos(s_doy * 2 * 2 * pi/366) + sin(s_doy * 2 * 2 * pi/366) +
                          cos(s_doy * 3 * 2 * pi/366) + sin(s_doy* 3 * 2 * pi/366)) 
                          )
```


```{r}
fit_zero_st <- glm(as.formula(form_zero_st), data = moorings_chirps, family = binomial, na.action = na.exclude)
anova(fit_zero_st, test = "Chisq")

```



```{r}
fit_zero_pr <- glm(as.formula(form_zero_pr), data = moorings_chirps, family = binomial, na.action = na.exclude)
anova(fit_zero_pr, test = "Chisq")
```


```{r}
predict_df <- data.frame(station = "Moorings", s_doy = 1:366,
                           s_doy_date = as.Date(1:366, origin = as.Date("1999/07/31")))
```

```{r}
predict_df[[paste0("station", "_", "Chirps")]] <- predict(fit_zero_st, 
                                                                 newdata = predict_df, 
                                                                 type = "response")
```

```{r}
predict_df[["Chirps"]] <- predict(fit_zero_pr, newdata = predict_df, 
                                         type = "response")
```

```{r}
predict_stack <- predict_df %>% melt(id.vars = c("station", "s_doy", "s_doy_date"), 
                                       variable.name = "product", value.name = "prob")
```

```{r}
predict_stack$product <- as.character(predict_stack$product)
```

```{r}
predict_stack$product2 <- predict_stack$product
```

```{r}
predict_stack$type <- "product1"
```

```{r}
predict_stack <- predict_stack %>% 
    mutate(type = ifelse(startsWith(product, "station"), "station1", type),
           product2 = ifelse(startsWith(product, "station"), 
                             substr(product, 9, nchar(product)), product2))
```

```{r}
predict_stack$type <- factor(predict_stack$type, levels = unique(predict_stack$type))
```

```{r}
predict_stack_lst <- list()
predict_stack_lst[[length(predict_stack_lst) + 1]] <- predict_stack
```

```{r}
predict_stack_all <- bind_rows(predict_stack_lst)
```

```{r}
g <- ggplot(predict_stack, aes(x = s_doy_date, y = prob, colour = type, size = type)) +
    geom_line() +
    facet_wrap(~product2) +
    scale_size_manual(values = c(0.8, rep(0.6, 4))) +
    scale_color_manual(values = c("black", c25[1:4])) +
    scale_x_date(date_breaks = "2 months", date_labels = "%b") +
    ggtitle(paste("Chance of rain:", "Moorings"))
  print(g)
  ggsave(here("results", "markov_test", 
              paste0("zambia_", "markov_zero", "_station_", "Moorings", ".png")),
         plot = g, width = 12, height = 6)
```


```{r}
first_order_test_df <- moorings_chirps %>% filter((date >= as.Date("2007-08-01")) & date <= as.Date("2008-07-31"))
```

```{r}
first_order_train_df <- moorings_chirps %>% filter((date < as.Date("2007-08-01")) | date > as.Date("2008-07-31"))
```

```{r}
# Fitting first-order MC for station
form_one_st <- rainday ~ ((cos(s_doy * 1 * 2 * pi/366) + sin(s_doy * 1 * 2 * pi/366) + 
                          cos(s_doy * 2 * 2 * pi/366) + sin(s_doy * 2 * 2 * pi/366) +
                          cos(s_doy * 3 * 2 * pi/366) + sin(s_doy* 3 * 2 * pi/366)) * 
                          prev1)
```

```{r}
fit_one_st <- glm(as.formula(form_one_st), data = first_order_train_df, family = binomial, na.action = na.exclude)
anova(fit_one_st, test = "Chisq")
```

```{r}
# Fitting first-order MC for station
form_one_pr <- pr_rainday ~ ((cos(s_doy * 1 * 2 * pi/366) + sin(s_doy * 1 * 2 * pi/366) + 
                          cos(s_doy * 2 * 2 * pi/366) + sin(s_doy * 2 * 2 * pi/366) +
                          cos(s_doy * 3 * 2 * pi/366) + sin(s_doy* 3 * 2 * pi/366)) * 
                          pr_prev1)
```

```{r}
fit_one_pr <- glm(as.formula(form_one_pr), data = first_order_train_df, family = binomial, na.action = na.exclude)
anova(fit_one_pr, test = "Chisq")
```

```{r}
predict_df_one <- first_order_test_df %>% select(station, date, s_doy, rainday, prev1, pr_rainday, pr_prev1)
predict_df_one$s_doy_date <- predict_df_one$date
```

```{r}
predict_df_one[[paste0("station", "_", "Chirps")]] <- predict(fit_one_st, 
                                                                 newdata = predict_df_one, 
                                                                 type = "response")
```

```{r}
predict_df_one[["Chirps"]] <- predict(fit_one_pr, newdata = predict_df_one, 
                                         type = "response")
```

```{r}
predict_df_one <- predict_df_one %>% mutate(prev1 = ifelse(prev1 == TRUE, "w", "d"),
                          pr_prev1 = ifelse(pr_prev1 ==TRUE, "w", "d"))
```


```{r}
date_range <- as.Date(c("2007-08-01", "2008-07-31"))
library(tidyverse)
reshaped_df1 <- predict_df_one %>%
  mutate(line_type_prev1 = ifelse(prev1 == "w", "solid", "dashed"),
         line_type_pr_prev1 = ifelse(pr_prev1 == "w", "solid", "dashed")) %>%
  # Reshape the data by pivoting the "station_Chirps" and "Chirps" columns
  pivot_longer(cols = c(station_Chirps, Chirps),
               names_to = "variable",
               values_to = "value") %>%
  # Determine the line type based on the variable and line_type_prev1/pr_prev1 values
  mutate(line_type = ifelse(variable == "Chirps", line_type_pr_prev1, line_type_prev1))

# Create the plot using ggplot
# Create the plot using ggplot
fp <- ggplot(reshaped_df1, aes_string(x = "date", y = "value", color = "variable", linetype = "line_type")) +
  geom_line() +
  # Customize the color scale for the legend
  scale_color_manual(values = c("station_Chirps" = "blue", "Chirps" = "red"),
                     labels = c("station_Chirps" = "Station", "Chirps" = "Chirps")) +
  scale_x_date(limits = date_range, 
               date_breaks = "1 month", date_labels = "%b", expand = c(0, 0)) +
  # Customize the linetype scale for the legend
  scale_linetype_manual(values = c("solid", "dashed"),
                        labels = c("D", "W")) +
  # Add x-axis and y-axis labels
  xlab("Date") +
  ylab("Value") +
  # Add a plot title
  ggtitle("Line Plot of Chirps and Station Chirps") +
  # Customize the theme
  theme_minimal()
ggsave(here("results", "markov_test", 
            paste0("zambia_", "markov_first_order", "_station_", "Moorings_chirps", ".png")),
       plot = fp, width = 12, height = 6)

fp

```

```{r, warning=FALSE}
date_range <- as.Date(c("2007-08-01", "2008-07-31"))
library(tidyverse)
reshaped_df <- predict_df_one %>%
  mutate(line_type_prev1 = ifelse(prev1 == "w", "solid", "dashed"),
         line_type_pr_prev1 = ifelse(pr_prev1 == "w", "solid", "dashed")) %>%
  # Reshape the data by pivoting the "station_Chirps" and "Chirps" columns
  pivot_longer(cols = c(station_Chirps, Chirps),
               names_to = "variable",
               values_to = "value") %>%
  # Determine the line type based on the variable and line_type_prev1/pr_prev1 values
  mutate(line_type = ifelse(variable == "Chirps", line_type_pr_prev1, line_type_prev1))

# Create the plot using ggplot
# Create the plot using ggplot
ggplot(reshaped_df, aes(x = date, y = value, color = variable, linetype = line_type)) +
  geom_line() +
  # Customize the color scale for the legend
  scale_color_manual(values = c("station_Chirps" = "blue", "Chirps" = "red"),
                     labels = c("station_Chirps" = "Station", "Chirps" = "Chirps")) +
  scale_x_date(limits = date_range, 
               date_breaks = "1 month", date_labels = "%b", expand = c(0, 0)) +
  # Customize the linetype scale for the legend
  scale_linetype_manual(values = c("solid", "dashed"),
                        labels = c("D", "W")) +
  # Add x-axis and y-axis labels
  xlab("Date") +
  ylab("Value") +
  labs(color = "type", linetype = "lag1") +  # Modify the legend titles
  ggtitle("Chance of rain: Moorings") +
  ylab("Probability") +
  xlab("Day of Year")
  # Add a plot title
  ggtitle("Line Plot of Chirps and Station Chirps") +
  # Customize the theme
  theme_minimal()

```


```{r markov_chain_setup}
zambia_markov <- zm_long_st %>%
  mutate(rainday = rain > 0.85,
         pr_rainday1 = pr_rain > 0.85,
         pr_rainday3 = pr_rain > 3,
         pr_rainday4 = pr_rain > 4,
         pr_rainday5 = pr_rain > 5,
         rainday_lag = dplyr::lag(rainday, n=1),
         pr_rainday1_lag = dplyr::lag(pr_rainday1, n=1),
         pr_rainday3_lag = dplyr::lag(pr_rainday3, n=1),
         pr_rainday4_lag = dplyr::lag(pr_rainday4, n=1),
         pr_rainday5_lag = dplyr::lag(pr_rainday5, n=1))

zambia_markov$rainday_lag <- factor(zambia_markov$rainday_lag)
zambia_markov$pr_rainday1_lag <- factor(zambia_markov$pr_rainday1_lag)
zambia_markov$pr_rainday3_lag <- factor(zambia_markov$pr_rainday3_lag)
zambia_markov$pr_rainday4_lag <- factor(zambia_markov$pr_rainday4_lag)
zambia_markov$pr_rainday5_lag <- factor(zambia_markov$pr_rainday5_lag)


basic_form <- . ~ (cos(s_doy * 1 * 2 * pi/366) + sin(s_doy * 1 * 2 * pi/366) +
                          cos(s_doy * 2 * 2 * pi/366) + sin(s_doy * 2 * 2 * pi/366) +
                          cos(s_doy * 3 * 2 * pi/366) + sin(s_doy* 3 * 2 * pi/366))

f_first_order_station <- update.formula(basic_form,  rainday ~ (.) * rainday_lag)

f_first_order_product1 <- update.formula(basic_form,  pr_rainday1 ~ (.) * pr_rainday1_lag)
f_zero_order_product_3thres <- update.formula(basic_form,  pr_rainday3 ~ (.) * pr_rainday3_lag)
f_zero_order_product_4thres <- update.formula(basic_form,  pr_rainday4 ~ (.) * pr_rainday4_lag)
f_zero_order_product_5thres <- update.formula(basic_form,  pr_rainday5 ~ (.) * pr_rainday5_lag)

```

```{r}
#select a period with no NAs in across all the products and use as test
first_order_test_df <- zambia_markov %>% filter((date >= as.Date("2004-08-01")) & date <= as.Date("2005-07-31"))
```

```{r}
first_order_train_df <- zambia_markov %>% filter((date < as.Date("2004-08-01")) | date > as.Date("2005-07-31"))
```


```{r}
predict_stack_lst <- list()
for (s in seq_along(stations)){
  predict_df_1 <- first_order_test_df %>% filter(station == stations[s])
  predict_df_1$s_doy_date <- predict_df_1$date
  
  dat <- first_order_train_df %>%
    filter(station == stations[s])
  
  for(i in seq_along(products)) {
    dat_prod <- dat %>%
      filter(product == products[i]) %>% 
      filter(!is.na(rain) & !is.na(pr_rain))
    first_order_station1 <- glm(f_first_order_station, data = dat_prod, family = binomial)
    first_order_product1 <- glm(f_first_order_product1, data = dat_prod, family = binomial)
    predict_df_m <- predict_df_1 %>%
      filter(product == products[i])
    predict_df_m[[paste0("station", "_", products[i])]] <- predict(first_order_station1, 
                                                                 newdata = predict_df_m, 
                                                                 type = "response")
    predict_df_m[[products[i]]] <- predict(first_order_product1, newdata = predict_df_m, 
                                         type = "response")

    
   predict_df_m <- predict_df_m %>% mutate(line_type_prev1 = ifelse(rainday_lag == TRUE, "solid", "dashed"),
         line_type_pr_prev1 = ifelse(pr_rainday1_lag == TRUE, "solid", "dashed")) %>%
      # Reshape the data by pivoting the "station_Chirps" and "Chirps" columns
      pivot_longer(cols = c(paste0("station", "_", products[[i]]), products[[i]]),
               names_to = "variable",
               values_to = "value") %>%
  # Determine the line type based on the variable and line_type_prev1/pr_prev1 values
  mutate(line_type = ifelse(variable == products[[i]], line_type_pr_prev1, line_type_prev1))

  # Define the color scale values and labels
  color_values <- c(paste0("station_", products[[i]]) = "blue", products[[i]] = "red")
  color_labels <- c(paste0("station_", products[[i]]) = "Station", products[[i]] = "Product")
    
  #plot graph
  p11 <- ggplot(predict_df_m, aes_string(x = "s_doy_date", y = "value", color = "variable", linetype = "line_type")) +
  geom_line() +
  # Customize the color scale for the legend
  cale_color_manual(values = color_values, labels = color_labels) +
  scale_x_date(date_breaks = "2 months", date_labels = "%b", expand = c(0, 0)) +
  # Customize the linetype scale for the legend
  scale_linetype_manual(values = c("solid", "dashed"),
                        labels = c("D", "W")) +
  # Add x-axis and y-axis labels
  xlab("Day of Year") +
  ylab("Probability") +
  labs(color = "type", linetype = "lag1") +
  ggtitle(paste("Chance of rain:", stations[s], "_", products[i])) 
  ggsave(here("results", "markov_test", 
              paste0("zambia_", "markov_zero", stations[s], "_", products[i], ".png")),
         plot = p11, width = 12, height = 6)
  #print(p11)
  }
  rm(predict_df_m)
}
```
```{r}
predict_stack_lst <- list()
for (s in seq_along(stations)){
  predict_df_1 <- first_order_test_df %>% filter(station == stations[s])
  predict_df_1$s_doy_date <- predict_df_1$date
  
  dat <- first_order_train_df %>%
    filter(station == stations[s])
  
  for(i in seq_along(products)) {
    dat_prod <- dat %>%
      filter(product == products[i]) %>% 
      filter(!is.na(rain) & !is.na(pr_rain))
    first_order_station1 <- glm(f_first_order_station, data = dat_prod, family = binomial)
    first_order_product1 <- glm(f_first_order_product1, data = dat_prod, family = binomial)
    predict_df_m <- predict_df_1 %>%
      filter(product == products[i])
    predict_df_m[[paste0("station", "_", products[i])]] <- predict(first_order_station1, 
                                                                 newdata = predict_df_m, 
                                                                 type = "response")
    predict_df_m[[products[i]]] <- predict(first_order_product1, newdata = predict_df_m, 
                                           type = "response")
    
    predict_df_m <- predict_df_m %>% 
      mutate(line_type_prev1 = ifelse(rainday_lag == TRUE, "solid", "dashed"),
             line_type_pr_prev1 = ifelse(pr_rainday1_lag == TRUE, "solid", "dashed")) %>%
      # Reshape the data by pivoting the "station_Chirps" and "Chirps" columns
      pivot_longer(cols = c(paste0("station", "_", products[[i]]), products[[i]]),
                   names_to = "variable",
                   values_to = "value") %>%
      # Determine the line type based on the variable and line_type_prev1/pr_prev1 values
      mutate(line_type = ifelse(variable == products[[i]], line_type_pr_prev1, line_type_prev1))
    
    # Define the color scale values and labels
    color_values <- setNames(c("blue", "red"), c(paste0("station_", products[i]), products[i]))
    color_labels <- setNames(c("Station", "Product"), c(paste0("station_", products[i]), products[i]))
    
    # Plot graph
    p11 <- ggplot(predict_df_m, aes_string(x = "s_doy_date", y = "value", color = "variable", linetype = "line_type")) +
      geom_line() +
      # Customize the color scale for the legend
      scale_color_manual(values = color_values, labels = color_labels) +
      scale_x_date(date_breaks = "2 months", date_labels = "%b", expand = c(0, 0)) +
      # Customize the linetype scale for the legend
      scale_linetype_manual(values = c("solid", "dashed"), labels = c("D", "W")) +
      # Add x-axis and y-axis labels
      xlab("Day of Year") +
      ylab("Probability") +
      labs(color = "type", linetype = "lag1") +
      ggtitle(paste("Chance of rain:", stations[s], "_", products[i])) 
  ggsave(here("results", "markov_test", 
              paste0("zambia_", "markov_zero", stations[s], "_", products[i], ".png")),
         plot = p11, width = 12, height = 6)
  #print(p11)
  }
}
```



